import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import React, { Suspense } from 'react';
import NavigationBar from '@/components/NavigationBar';
import { TeamProvider } from '@/context/TeamContext';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen antialiased`}
      >
        <TeamProvider>
          <Suspense
            fallback={<nav className="h-12 w-full border-b bg-white" />}
          >
            <NavigationBar />
          </Suspense>
          <main className="p-8">{children}</main>
        </TeamProvider>
      </body>
    </html>
  );
}
